---
title: "2019 Democratic Debates data project"
author: "Jane Doe"
output: github_document
---

```{r setup, include=FALSE}
# create image folder ----
if (!file.exists("figs/")) {
    dir.create("figs/")
}
# create data folder ----
if (!file.exists("data/")) {
    dir.create("data/")
}
knitr::opts_chunk$set(
    echo = TRUE, # show all code
    tidy = FALSE, # cleaner code printing
    size = "small", # smaller code
    fig.path = "figs/") 
knitr::opts_knit$set(
    width = 78)
base::options(tibble.print_max = 25,
              tibble.width = 78)
```

```{r packages, warning=FALSE, message=FALSE}
library(tidyverse)
library(Hmisc)
library(janitor)
library(magrittr)
library(rtweet)
library(visdat)
library(inspectdf)
```

# Motivation

We read an interesting article on fivethirtyeight about the democratic debates in June of 2019. In particular, the image below that displays how voters had changed their minds after watching the candidates. 

## Import data 

The code chunk below imports the raw data.

```{r import-data}
# where are the data?
fs::dir_tree("data/raw")
```

